# My Workbook through the intro to linear algebra

[intro to linear algebra](../notebooks/1-intro-to-linear-algebra.ipynb)

This is my work that I'm doing following along with this notebook.

Should I come into any sections that I don't understand or otherwise can't perform, I'll comment above the code and use the other section as guidance.

In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [1]:
x = 25
x

25

In [2]:
type(x)

int

In [3]:
y = 3

In [4]:
py_sum = x + y
py_sum

28

In [5]:
type(py_sum)

int

In [6]:
x_float = 25.0
float_sum = x_float + y
float_sum

28.0

In [7]:
type(float_sum)

float

checkout PyTorch library!

In [31]:
import torch

In [9]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [10]:
x_pt.shape

torch.Size([])

In [32]:
import tensorflow as tf

In [2]:
x_tf = tf.Variable(25, dtype=tf.int16) # dtype is optional
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [3]:
x_tf.shape

TensorShape([])

In [4]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [5]:
x_tf + y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [6]:
tf_sum = tf.add(x_tf, y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [7]:
tf_sum.numpy()

28

In [8]:
type(tf_sum.numpy())

numpy.int16

In [9]:
tf_float = tf.Variable(25., dtype=tf.float16)
tf_float

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=25.0>

In [11]:
x = np.array((25, 2, 5))
x

array([25,  2,  5])

In [12]:
len(x)

3

In [14]:
x.shape

(3,)

In [15]:
type(x)

numpy.ndarray

In [16]:
x[0]

25

In [17]:
type(x[0])

numpy.int64

In [20]:
x_t = x.T
x_t

array([25,  2,  5])

In [21]:
x_t.shape

(3,)

In [22]:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [23]:
y.shape

(1, 3)

In [25]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [26]:
y_t.shape

(3, 1)

In [27]:
y_t.T

array([[25,  2,  5]])

In [28]:
y_t.T.shape

(1, 3)

In [29]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [33]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [34]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>

$L^2$ Norm sample

In [35]:
x

array([25,  2,  5])

In [36]:
(25**2 + 2**2 + 5**2)**(1/2) # square each element, sum them up, and take square root (L^2 Norm) (Eucledean distance)

25.573423705088842

In [37]:
np.linalg.norm(x) # numpy method for linear algebra L^2 Norm calculation

25.573423705088842

$L^1$ Norm Sample

In [38]:
x

array([25,  2,  5])

In [39]:
np.abs(25) + np.abs(2) + np.abs(5)

32

In [40]:
x

array([25,  2,  5])

In [41]:
(25**2 + 2**2 + 5**2)

654

In [42]:
np.dot(x, x)

654

In [43]:
x

array([25,  2,  5])

In [44]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

In [45]:
i = np.array([1,0])
i

array([1, 0])

In [46]:
j = np.array([0,1])
j

array([0, 1])

In [47]:
np.dot(i, j)

0

In [49]:
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [50]:
X.shape

(3, 2)

In [51]:
X.size

6

In [52]:
X[:,0] # this selects the left column of matrix X (zero-indexed)

array([25,  5,  3])

In [53]:
X[1,:] # select the middle row of Matrix X

array([ 5, 26])

In [54]:
X[0:2,0:2] # another slicing-by-index example:

array([[25,  2],
       [ 5, 26]])

In [55]:
X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [56]:
X_pt.shape

torch.Size([3, 2])

In [57]:
X_pt[1,:]

tensor([ 5, 26])

In [58]:
X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]], dtype=int32)>

In [60]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [61]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

In [62]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26], dtype=int32)>

In [63]:
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [64]:
X.T

array([[25,  5,  3],
       [ 2, 26,  7]])

In [65]:
X_pt.T

tensor([[25,  5,  3],
        [ 2, 26,  7]])

In [66]:
tf.transpose(X_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[25,  5,  3],
       [ 2, 26,  7]], dtype=int32)>

In [67]:
X*2

array([[50,  4],
       [10, 52],
       [ 6, 14]])

In [68]:
X+2

array([[27,  4],
       [ 7, 28],
       [ 5,  9]])

In [69]:
X*2+2

array([[52,  6],
       [12, 54],
       [ 8, 16]])

In [70]:
torch.add(torch.mul(X_pt, 2), 2)

tensor([[52,  6],
        [12, 54],
        [ 8, 16]])

In [71]:
X_tf*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [72]:
tf.add(tf.multiply(X_tf, 2), 2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>